"""align model constraints and indexes

Revision ID: 4a6ce213c5d7
Revises: 0003_role_permissions
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a6ce213c5d7'
down_revision = '0003_role_permissions'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'level',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.alter_column('cameras', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.alter_column('detections', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.create_index(op.f('ix_detections_track_id'), 'detections', ['track_id'], unique=False)
    op.alter_column('events', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('events', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.alter_column('model_versions', 'metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.alter_column('tracks', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('zones', 'polygon',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.alter_column('zones', 'polygon',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.alter_column('tracks', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.alter_column('model_versions', 'metrics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.alter_column('events', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('events', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_detections_track_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.alter_column('detections', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.alter_column('cameras', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.alter_column('alerts', 'level',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
